<a href="https://colab.research.google.com/github/NayanthaDhasun/NorthStar_Database_Analytics/blob/main/R_Analytics_Analytics_ASG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
install.packages("sqldf")
install.packages("readr")
install.packages("dplyr")
install.packages("ggplot2")

library(sqldf)
library(readr)
library(dplyr)
library(ggplot2)

deliveries <- read_csv("deliveries.csv")
hubs <- read_csv("hubs.csv")
drivers <- read_csv("drivers.csv")
vehicles <- read_csv("vehicles.csv")
complaints <- read_csv("complaints.csv")

head(deliveries)
str(deliveries)

query1 <- sqldf("
SELECT delivery_status,
       COUNT(*) AS total_deliveries,
       ROUND(AVG(route_distance_km),2) AS avg_distance,
       ROUND(AVG(customer_rating_post_delivery),2) AS avg_customer_rating,
       ROUND(AVG(fuel_or_charge_cost),2) AS avg_operational_cost
FROM deliveries
GROUP BY delivery_status
ORDER BY total_deliveries DESC
")

query1

query2 <- sqldf("
SELECT h.hub_name,
       h.zone,
       COUNT(d.delivery_id) AS total_deliveries,
       SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,
       ROUND(AVG(d.customer_rating_post_delivery),2) AS avg_customer_rating,
       ROUND(AVG(d.fuel_or_charge_cost),2) AS avg_cost
FROM deliveries d
JOIN hubs h
ON d.hub_id = h.hub_id
GROUP BY h.hub_name, h.zone
ORDER BY failed_deliveries DESC
")

query2

query3 <- sqldf("
SELECT dr.driver_id,
       dr.base_zone,
       dr.years_experience,
       dr.training_score,
       dr.driver_rating,
       COUNT(d.delivery_id) AS total_deliveries,
       SUM(d.manual_route_override_count) AS total_route_overrides,
       ROUND(AVG(d.customer_rating_post_delivery),2) AS avg_customer_rating
FROM deliveries d
JOIN drivers dr
ON d.driver_id = dr.driver_id
GROUP BY dr.driver_id,
         dr.base_zone,
         dr.years_experience,
         dr.training_score,
         dr.driver_rating
ORDER BY total_route_overrides DESC
LIMIT 10
")

query3

query4 <- sqldf("
SELECT complaint_type,
       severity,
       COUNT(*) AS total_complaints,
       ROUND(AVG(resolution_days),2) AS avg_resolution_days,
       ROUND(AVG(compensation_amount),2) AS avg_compensation_amount
FROM complaints
GROUP BY complaint_type, severity
ORDER BY total_complaints DESC
")

query4

query5 <- sqldf("
SELECT v.vehicle_type,
       v.maintenance_status,
       COUNT(d.delivery_id) AS total_deliveries,
       SUM(CASE WHEN d.delivery_status = 'Failed' THEN 1 ELSE 0 END) AS failed_deliveries,
       ROUND(AVG(v.battery_health_pct),2) AS avg_battery_health,
       ROUND(AVG(d.fuel_or_charge_cost),2) AS avg_operational_cost
FROM deliveries d
JOIN vehicles v
ON d.vehicle_id = v.vehicle_id
GROUP BY v.vehicle_type, v.maintenance_status
ORDER BY failed_deliveries DESC
")

query5

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Rows: 950 Columns: 13
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (6): delivery_id, order_id, driver_id, vehicle_id, hub_id, delivery_status
dbl  (5): route_distance_km, manual_route_override_count, proof_of_completio...
dttm (2): dispatch_time, delivery_completed_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 8 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): hub_id, hub_name, zone, hub_type
dbl (1): capacity_score

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 170 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr (4): driver_id, base_zone, employment_type, shift_preference
dbl (4): years_experience, training_score, driver_rating, active_flag

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 120 Columns: 8
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (5): vehicle_id, vehicle_type, assigned_zone, maintenance_status, telem...
dbl  (2): battery_health_pct, odometer_km
dttm (1): commission_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Rows: 320 Columns: 10
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (7): complaint_id, customer_id, order_id, complaint_type, channel, seve...
dbl  (2): resolution_days, compensation_amount
dttm (1): created_at

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at delivery_status route_distance_km
1 2024-06-19 09:05:59   Failed          17.26
2 2025-01-11 17:39:00   OnTime          10.34
3 2025-06-02 21:45:32   OnTime           7.92
4 2024-03-09 23:30:08   Delayed         16.42
5 2025-09-21 15:45:34   OnTime          14.52
6 2024-09-12 17:11:52   Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

spc_tbl_ [950 × 13] (S3: spec_tbl_df/tbl_df/tbl/data.frame)
 $ delivery_id                  : chr [1:950] "DL00001" "DL00002" "DL00003" "DL00004" ...
 $ order_id                     : chr [1:950] "O00938" "O00004" "O00639" "O00313" ...
 $ driver_id                    : chr [1:950] "D004" "D138" "D006" "D116" ...
 $ vehicle_id                   : chr [1:950] "V056" "V007" "V049" "V055" ...
 $ hub_id                       : chr [1:950] "H05" "H02" "H02" "H02" ...
 $ dispatch_time                : POSIXct[1:950], format: "2024-06-18 10:57:00" "2025-01-11 18:45:00" ...
 $ delivery_completed_at        : POSIXct[1:950], format: "2024-06-19 09:05:59" "2025-01-11 17:39:00" ...
 $ delivery_status              : chr [1:950] "Failed" "OnTime" "OnTime" "Delayed" ...
 $ route_distance_km            : num [1:950] 17.26 10.34 7.92 16.42 14.52 ...
 $ manual_route_override_count  : num [1:950] 1 1 0 0 1 0 0 1 1 1 ...
 $ proof_of_completion_missing  : num [1:950] 0 0 0 0 0 0 0 0 0 0 ...
 $ customer_rating_post_delivery: num [1:950] 3.07 5 4.98 4.18 4.18 1.57 4.64 3.76 3.7 3.2 ...
 $ fuel_or_charge_cost          : num [1:950] 12.05 13.41 8.51 13.62 9.22 ...
 - attr(*, "spec")=
  .. cols(
  ..   delivery_id = col_character(),
  ..   order_id = col_character(),
  ..   driver_id = col_character(),
  ..   vehicle_id = col_character(),
  ..   hub_id = col_character(),
  ..   dispatch_time = col_datetime(format = ""),
  ..   delivery_completed_at = col_datetime(format = ""),
  ..   delivery_status = col_character(),
  ..   route_distance_km = col_double(),
  ..   manual_route_override_count = col_double(),
  ..   proof_of_completion_missing = col_double(),
  ..   customer_rating_post_delivery = col_double(),
  ..   fuel_or_charge_cost = col_double()
  .. )
 - attr(*, "problems")=<pointer: 0x5c35ec7dc790>

  delivery_status total_deliveries avg_distance avg_customer_rating
1 OnTime          616              13.78        4.28
2 Delayed         202              14.67        3.11
3 Failed          132              13.37        3.05
  avg_operational_cost
1 12.68
2 13.14
3 13.15

  hub_name       zone      total_deliveries failed_deliveries
1 Midtown Relay  Central   128              26
2 Central Core   Central   115              23
3 North Exchange North     136              17
4 West Gate      West      127              16
5 Airport Hub    Airport   104              15
6 Riverside Hub  Riverside 115              14
7 East Dock      East      119              11
8 South Link     South     106              10
  avg_customer_rating avg_cost
1 3.88                11.71
2 3.67                13.69
3 3.84                12.76
4 3.92                13.17
5 3.88                13.32
6 3.88                12.92
7 3.90                12.74
8 3.95                12.57

   driver_id base_zone years_experience training_score driver_rating
1  D127      CENTRAL   10               61.5           4.19
2  D087      north     13               73.3           4.43
3  D130      WEST       8               71.2           3.64
4  D108      South     10               70.6           4.33
5  D131      SOUTH      9               86.7           4.26
6  D069      NORTH      2               61.5           5.00
7  D105      RiverSide  2               82.0           3.71
8  D017      EAST       1                 NA           4.34
9  D028      North     11               83.0           4.07
10 D008      SOUTH      9               84.1           3.88
   total_deliveries total_route_overrides avg_customer_rating
1   6               17                    4.10
2  12               16                    3.82
3   8               16                    3.80
4  11               15                    4.41
5   9               15                    3.66
6   7               14                    3.94
7   7               14                    4.21
8  10               13                    3.68
9   7               13                    3.54
10  8               12                    3.92

   complaint_type    severity total_complaints avg_resolution_days
1  Delay             Medium   56                5.96
2  MissedPickup      Medium   37                6.16
3  DriverBehaviour   Medium   31                5.42
4  Delay             Low      27                6.48
5  AppIssue          Medium   25                7.36
6  Delay             High     18               12.44
7  DriverBehaviour   High     16               13.75
8  MissedPickup      High     16               11.56
9  AppIssue          Low      15                6.07
10 AppIssue          High     13               13.92
11 SupportExperience Medium   12                6.17
12 MissedPickup      Low      11                6.91
13 Billing           Medium    9                5.78
14 Damage            High      7               15.43
15 Damage            Low       6                6.83
16 SupportExperience Low       5                6.20
17 Billing           High      4               12.00
18 DriverBehaviour   Low       4                7.00
19 Billing           Low       3                8.00
20 SupportExperience High      3               14.67
21 Damage            Medium    2               10.50
   avg_compensation_amount
1  18.21
2  17.91
3  15.88
4   8.16
5  16.11
6  36.54
7  38.39
8  43.07
9  13.25
10 34.05
11 18.68
12  8.14
13 16.90
14 37.26
15 10.83
16  3.34
17 52.32
18  9.04
19  6.86
20 33.88
21 16.94

   vehicle_type maintenance_status total_deliveries failed_deliveries
1  CargoVan     InRepair            68              22
2  Hybrid       InRepair            71              21
3  Diesel       InRepair            55              17
4  EV           InRepair            60              17
5  Hybrid       Active             131              15
6  CargoVan     Active             117              11
7  EV           Active             214              11
8  Diesel       Active              80               8
9  CargoVan     Scheduled           38               5
10 EV           Scheduled           65               2
11 Hybrid       Scheduled           42               2
12 Diesel       Scheduled            9               1
   avg_battery_health avg_operational_cost
1  69.82              12.46
2  83.27              13.13
3  75.65              13.30
4  77.79              12.78
5  73.67              12.51
6  74.41              13.37
7  83.00              12.98
8  67.02              12.43
9  68.96              11.88
10 82.92              12.88
11 80.56              12.64
12 81.33              13.93